// import Vue from 'vue'
// import atui from '../../src/'

// describe('atui', () => {
//   it('should has modules in atui', () => {
//     expect('Affix' in atui).toBeTruthy()
//     expect('Alert' in atui).toBeTruthy()
//     expect('Badge' in atui).toBeTruthy()
//     expect('Breadcrumb' in atui).toBeTruthy()
//     expect('Button' in atui).toBeTruthy()
//     expect('Calendar' in atui).toBeTruthy()
//     expect('Card' in atui).toBeTruthy()
//     expect('Carousel' in atui).toBeTruthy()
//     expect('Cascader' in atui).toBeTruthy()
//     expect('Checkbox' in atui).toBeTruthy()
//     expect('Col' in atui).toBeTruthy()
//     expect('DatePicker' in atui).toBeTruthy()
//     expect('Dropdown' in atui).toBeTruthy()
//     expect('Form' in atui).toBeTruthy()
//     expect('Icon' in atui).toBeTruthy()
//     expect('Input' in atui).toBeTruthy()
//     expect('Menu' in atui).toBeTruthy()
//     expect('Message' in atui).toBeTruthy()
//     expect('Modal' in atui).toBeTruthy()
//     expect('Pagination' in atui).toBeTruthy()
//     expect('Popover' in atui).toBeTruthy()
//     expect('QueueAnim' in atui).toBeTruthy()
//     expect('Radio' in atui).toBeTruthy()
//     expect('Row' in atui).toBeTruthy()
//     expect('Select' in atui).toBeTruthy()
//     expect('Slider' in atui).toBeTruthy()
//     expect('Spin' in atui).toBeTruthy()
//     expect('Steps' in atui).toBeTruthy()
//     expect('Switch' in atui).toBeTruthy()
//     expect('Table' in atui).toBeTruthy()
//     expect('Tabs' in atui).toBeTruthy()
//     expect('Tag' in atui).toBeTruthy()
//     // expect('TimePicker' in atui).toBeTruthy()
//     expect('Tooltip' in atui).toBeTruthy()
//     expect('Uploader' in atui).toBeTruthy()
//   })
// })
